panels = {
    1: '<p>'
    'You are about to participate in an experiment on decision-making in economics. '
    'This study is based on your voluntary participation and your data will be treated confidentially and anonymously. '
    'This experiment is composed of three phases: <br>'
    ' 1) Instructions<br>'
    ' 2) A game<br>'
    ' 3) A short survey<br>'
    '<b>Please note that you have 8 minutes to read these instructions. <br>'
       'After that the game will start automatically.</b>'
    '</p>',
    2:  '<p>' 
        'In the game there are <b>two types</b> of players: the <b>blue</b> and <b>yellow</b> one.'
        'You will be randomly attributed to one color in the beginning of the game.'
        'Your type will <b>remain</b> the same all along the game.<br>'
        'Note that different types have different multipliers (the latter is displayed on the character tshirt).'
        '<br><br><img src="/static/img/2_players.png"><br><br>'
        'In each round you will be randomly matched with another player. A round is divided into 3 steps.<br>' 
        '1) you will be asked to either display or hide your type, so that the other player will know your type or not.<br>'
        '2) you will be asked to contribute (a certain number of points) to a public pot.<br>' 
        '3) Your contribution will be multiplied according to your type and the points put in the public pot will be equally distributed among the players. <br>'
        'Thereafter, you will continue to the next round.'
        '</p>',
    3:  '<p>' 
        ''
        'You will be randomly attributed to one color in the beginning of the game.'
        'Your type will <b>remain</b> the same all along the game.<br>'
        'Note that different types have different multipliers (the latter is displayed on the character tshirt).'
        '<br><br><img src="/static/img/2_players.png"><br><br>'
        'In each round you will be randomly matched with another player. A round is divided into 3 steps.<br>' 
        '1) you will be asked to either display or hide your type, so that the other player will know your type or not.<br>'
        '2) you will be asked to contribute (a certain number of points) to a public pot.<br>' 
        '3) Your contribution will be multiplied according to your type and the points put in the public pot will be equally distributed among the players. <br>'
        'Thereafter, you will continue to the next round.'
        '</p>'
}

titles = {
    1: 'Welcome!', 2: 'Short summary of the game'
}