# Generated by Django 2.2.12 on 2021-02-20 21:16

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0002_player_disclose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='disclose',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to reveal your multiplier to the other player?'),
        ),
    ]
