# Generated by Django 2.2.12 on 2021-02-20 21:19

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_covid', '0003_auto_20210220_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='multiplier',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
