# Generated by Django 2.2.12 on 2021-02-26 14:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_covid', '0004_player_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='treatment',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='disclose',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Do you want to reveal your multiplier?'),
        ),
    ]
